/*
 * (C) Copyright 2002
 * Gerald Van Baren, Custom IDEAS, vanbaren@cideas.com
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */
#define DEBUG
/*
 * SPI Read/Write Utilities
 */
#include <common.h>
#include <command.h>
#include <dm.h>
#include <errno.h>
#include <spi.h>
#include <phy.h>
#include <miiphy.h>
#include <malloc.h>
#include <phy_interface.h>
#include <asm-generic/gpio.h>
#include <linux/delay.h>

/*-----------------------------------------------------------------------
 * Definitions
 */

#define MAX_SPI_BYTES 32	/* Maximum number of bytes we can handle */

/* Define following for debug */
#undef SPI_BCM53_DEBUG

/* BCM53xx SPI register access names */
#define BCM53_SPI_DATA_REG		0xf0
#define BCM53_SPI_PAGE_REG		0xff
#define BCM53_SPI_STATUS_REG	0xfe
#define BCM53_SPI_STATUS_SPIF	(1 << 7)
#define BCM53_SPI_STATUS_RACK	(1 << 5)
#define BCM53_SPI_WRITE_CMD		0x61
#define BCM53_SPI_READ_CMD		0x60

#define BCM53_NR_OF_PHYS               4
#define BCM53_INTER_GPHY_REGISTER_BASE 0x10

/* Abort on non-zero error return */
#define ABORT_ON_ERROR(errorValue, label)									\
	do {																	\
		if (errorValue)											 			\
		{														   			\
			printf("%s:%d error %d\n", __func__, __LINE__, (errorValue));	\
			goto label;											 			\
		}																	\
	} while (0)

#ifdef SPI_BCM53_DEBUG
#define DUMP_BITS(str, out, in, nbits) dump_bits(str, out, in, nbits)
static void dump_bits(char *str, uchar *out, uchar *in, int nbits)
{
	int byteCnt = (nbits + 7)/8;
	int i;
	printf("%s ", str);
	for (i=0; i<byteCnt; ++i)
	{
		printf("%02x", out[i]);
	}
	printf(" in:");
	for (i=0; i<byteCnt; ++i)
	{
		printf("%02x", in[i]);
	}
	printf("\n");
}
#else
/* Disable debug */
#define DUMP_BITS(str, out, in, nbits)
#endif

struct bcmRegDesc {
	int regOffset;
	int bitWidth;
	const char * const name;
};

/* 'struct bcmRegDesc' initializer macro */
#define BCMREG_REG_DESC_INITIALIZER(regOffset, bitWidth, name) \
	{													  \
	regOffset,										 \
	bitWidth,										  \
	name,											  \
	}

/* Page 0x00: Control Register */
static struct bcmRegDesc bcmPage_00[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "Port Traffic Control (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x01, 8, "Port Traffic Control (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 8, "Port Traffic Control (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x03, 8, "Port Traffic Control (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x05, 8, "Port Traffic Control (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 8, "IMP Port Traffic Control"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 8, "IMP Port State Override"),
	BCMREG_REG_DESC_INITIALIZER(0x0f, 8, "LED Refresh Register"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "LED Function 0 Control"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "LED Function 1 Control"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "LED Function Map"),
	BCMREG_REG_DESC_INITIALIZER(0x16, 16, "LED Enable Port Map"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 16, "LED Mode Map 0"),
	BCMREG_REG_DESC_INITIALIZER(0x1a, 16, "LED Mode Map 1"),
	BCMREG_REG_DESC_INITIALIZER(0x1d, 8, "Post LED Control"),
	BCMREG_REG_DESC_INITIALIZER(0x21, 8, "Port Forward Control"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "Switch Control"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "Protected Port Protection"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "WAN Port Select Register"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "PAUSE Capability"),
	BCMREG_REG_DESC_INITIALIZER(0x2f, 8, "Reserve Multicast Control"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "ULF Packet Fwd"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "MLF Packet Fwd"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "MLF_IPCM_FWD_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "Rx Pause Pass Through"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "Tx Pause Pass Through"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "DIS_LEARN"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "SFT_LRN_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "LOW_PWR_EXP"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 8, "SCAN_RSLT_GP"),
	BCMREG_REG_DESC_INITIALIZER(0x5d, 8, "STS_OVERRIDE_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 8, "IMP_RGMII_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x65, 8, "PORT5_RGMII_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x6f, 8, "MDIO_DIRECT_ACCESS"),
	BCMREG_REG_DESC_INITIALIZER(0x75, 8, "MDIO_P5_ADDR"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 8, "MDIO_IMP_ADDR"),
	BCMREG_REG_DESC_INITIALIZER(0x79, 8, "WATCH_DOG_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 8, "PAUSE_FRM_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x81, 48, "PAUSE_ST_ADDR"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 8, "FAST_AGE_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x89, 8, "FAST_AGE_PORT"),
	BCMREG_REG_DESC_INITIALIZER(0x8a, 16, "FAST_AGE_VID"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 16, "LED_FUNC0_EXTD_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x92, 16, "LED_FUNC1_EXTD_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0xdd, 8, "PLL_STS"),
	BCMREG_REG_DESC_INITIALIZER(0xde, 16, "LOW_POWER_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 8, "TCAM_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "TCAM_CHKSUM_STS"),
};

/* Page 0x01: Status Register */
static struct bcmRegDesc bcmPage_01[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "LNKSTS"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "LNKSTSCHG"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 32, "SPDSTS"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "DUPSTS"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 32, "PAUSESTS"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "SRCADRCHG"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 48, "LSA_PORT"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 48, "LSA_MII_PORT"),
	BCMREG_REG_DESC_INITIALIZER(0x46, 48, "BIST_STS0"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 16, "BIST_STS1"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "STRAP_PIN_STATUS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 8, "DIRECT_INPUT_CTRL_VALUE"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 16, "RESET_STATUS"),
};

/* Page 0x02: Management/Mirroring Register */
static struct bcmRegDesc bcmPage_02[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "GMNGCFG"),
	BCMREG_REG_DESC_INITIALIZER(0x01, 8, "IMP0_PRT_ID"),
	BCMREG_REG_DESC_INITIALIZER(0x03, 8, "BRCM_HDR_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 32, "SPTAGT"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "MRCM_HDR_CTRL2"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "IPG_SHRNK_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "MIRCAPCTL"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "IGMIRCTL"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "IGMIRDIV"),
	BCMREG_REG_DESC_INITIALIZER(0x16, 48, "IGMIRMAC"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 16, "EGMIRCTL"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "EGMIRDIV"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 48, "EGMIRMAC"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "DEVICE_ID"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 8, "CHIP_REVID"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "HL_PRTC_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x54, 16, "RST_MIB_CNT_EN"),
};

/* Page 0x03: Interrupt Control Register */
static struct bcmRegDesc bcmPage_03[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "INT_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "INT_EN"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "IMP_SLEEP_TIMER"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "WLAN_SLEEP_TIMER"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 8, "PORT_SLEEP_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "INT_TRIGGER"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "LINK_STS_INT_EN"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "ENG_DET_INT_EN"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "LPI_STS_CHG_INT_EN"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 8, "CPU_RESOURCE_ARBITER"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "CPU_DATA_SHARE"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 64, "CPU_DATA_SHARE_1"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "PPOE_SESSION_PARSE_EN"),
};

/* Page 0x04: ARL Control Register */
static struct bcmRegDesc bcmPage_04[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "GARLCFG"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 48, "BPDU_MCADDR"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "MULTI PORT_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 64, "MULTIPORT_ADDR0"),	 
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "MPORTVEC0"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 64, "MULTIPORT_ADDR1"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "MPORTVEC1"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 64, "MULTIPORT_ADDR2"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "MPORTVEC2"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 64, "MULTIPORT_ADDR3"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "MPORTVEC3"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "MULTIPORT_ADDR4"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "MPORTVEC4"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 64, "MULTIPORT_ADDR5"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "MPORTFEC5"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "ARL_BIN_FULL_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 16, "ARL_BIN_FULL_FWD"),
};

/* Page 0x05: ARL/VTABLE Access Register */
static struct bcmRegDesc bcmPage_05[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "ARLA_RWCTL"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 48, "ARLA_MAC"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "ARLA_VID"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 64, "ARLA_MACVID_ENTRY0"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "ARLA_FWD_ENTRY0"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 64, "ARLA_MACVID_ENTRY1"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "ARLA_FWD_ENTRY1"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 64, "ARLA_MACVID_ENTRY2"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "ARLA_FWD_ENTRY2"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 64, "ARLA_MACVID_ENTRY3"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "ARLA_FWD_ENTRY3"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 8, "ARLA_SRCH_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x51, 16, "ARLA_SRCH_ADR"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 64, "ARLA_SRCH_RSLT_0_MACVID"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "ARLA_SRCH_RSLT_0"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 64, "ARLA_SRCH_RSLT_1_MACVID"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "ARLA_SRCH_RSLT_1"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 8, "ARLA_VTBL_RWCTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x81, 16, "ARLA_VTBL_ADDR"),
	BCMREG_REG_DESC_INITIALIZER(0x83, 32, "ARLA_VTBL_ENTRY"),
};

/* Page 0x10: Internal GPHY MII (port 0) Register */
static struct bcmRegDesc bcmPage_10[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "G_MIICTL (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "G_MIISTS (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "G_PHYIDH (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "G_PHYIDL (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "G_ANADV (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "G_ANLPA (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "G_ANEXP (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "G_ANNXP (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "G_LPNXP (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "G_B1000T_CTL (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "G_L1000T_STS (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "G_EXT_STS (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "G_PHY_EXT_CTL (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "G_PHY_EXT_STS (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "G_REC_ERR_CNT (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "G_FALSE_CARR_CNT (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "G_REC_NOTOK_CNT (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "G_DSP_COEFFICIENT (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "G_DSP_COEFFICIENT_ADDR (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "G_AUX_CTL (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "G_AUX_STS (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "G_INTERRUPT_STS (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "G_INTERRUPT_MSK (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "G_MISC_SHADOW (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "G_MASTER_SLAVE_SEED (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "G_TEST1 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "G_TEST2 (port 0)"),
};

/* Page 0x11: Internal GPHY MII (port 1) Register */
static struct bcmRegDesc bcmPage_11[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "G_MIICTL (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "G_MIISTS (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "G_PHYIDH (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "G_PHYIDL (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "G_ANADV (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "G_ANLPA (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "G_ANEXP (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "G_ANNXP (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "G_LPNXP (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "G_B1000T_CTL (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "G_L1000T_STS (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "G_EXT_STS (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "G_PHY_EXT_CTL (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "G_PHY_EXT_STS (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "G_REC_ERR_CNT (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "G_FALSE_CARR_CNT (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "G_REC_NOTOK_CNT (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "G_DSP_COEFFICIENT (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "G_DSP_COEFFICIENT_ADDR (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "G_AUX_CTL (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "G_AUX_STS (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "G_INTERRUPT_STS (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "G_INTERRUPT_MSK (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "G_MISC_SHADOW (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "G_MASTER_SLAVE_SEED (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "G_TEST1 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "G_TEST2 (port 1)"),
};

/* Page 0x12: Internal GPHY MII (port 2) Register */
static struct bcmRegDesc bcmPage_12[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "G_MIICTL (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "G_MIISTS (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "G_PHYIDH (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "G_PHYIDL (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "G_ANADV (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "G_ANLPA (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "G_ANEXP (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "G_ANNXP (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "G_LPNXP (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "G_B1000T_CTL (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "G_L1000T_STS (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "G_EXT_STS (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "G_PHY_EXT_CTL (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "G_PHY_EXT_STS (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "G_REC_ERR_CNT (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "G_FALSE_CARR_CNT (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "G_REC_NOTOK_CNT (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "G_DSP_COEFFICIENT (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "G_DSP_COEFFICIENT_ADDR (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "G_AUX_CTL (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "G_AUX_STS (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "G_INTERRUPT_STS (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "G_INTERRUPT_MSK (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "G_MISC_SHADOW (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "G_MASTER_SLAVE_SEED (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "G_TEST1 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "G_TEST2 (port 2)"),
};

/* Page 0x13: Internal GPHY MII (port 3) Register */
static struct bcmRegDesc bcmPage_13[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "G_MIICTL (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "G_MIISTS (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "G_PHYIDH (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "G_PHYIDL (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "G_ANADV (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "G_ANLPA (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "G_ANEXP (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "G_ANNXP (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "G_LPNXP (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "G_B1000T_CTL (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "G_L1000T_STS (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "G_EXT_STS (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "G_PHY_EXT_CTL (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "G_PHY_EXT_STS (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "G_REC_ERR_CNT (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "G_FALSE_CARR_CNT (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "G_REC_NOTOK_CNT (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "G_DSP_COEFFICIENT (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "G_DSP_COEFFICIENT_ADDR (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "G_AUX_CTL (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "G_AUX_STS (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "G_INTERRUPT_STS (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "G_INTERRUPT_MSK (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "G_MISC_SHADOW (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "G_MASTER_SLAVE_SEED (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "G_TEST1 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "G_TEST2 (port 3)"),
};

/* Page 0x14: Internal SerDes Port control/status */
static struct bcmRegDesc bcmPage_14[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "SerDes_MIICTL"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "SerDes_MIISTS"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "SerDes_ANADV"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "SerDes_ANLPA"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "SerDes_ANEXP"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x16, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x1a, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 16, "SerDes_Undefined"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "SerDes_EXT_STS"),
};

/* Page 0x20: Port MIB Counter (port 0) Register */
static struct bcmRegDesc bcmPage_20[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "TxOctets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TxDropPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "TxQPKTQ0 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "TxBroadcastPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "TxMulticasePkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "TxUnicastPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "TxCollision (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "TxSingleCollision (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "TxMultipleCollision (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "TxDeferredTransmit (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "TxLateCollision (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "TxExcessiveCollision (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "TxFrameInDisc (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "TxPausePkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "TxQPKTQ1 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "TxQPKTQ2 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "TxQPKTQ3 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "TxQPKTQ4 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "TxQPKTQ5 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "RxOctets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "RxUndersizePkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "RxPausePkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RxPkts64Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RxPkts65To127Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RxPkts128To255Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RxPkts256To511Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RxPkts512To1023Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RxPkts1024ToMaxOctets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RxOversizePkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "RxJabbers (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "RxAlignementErrors (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "RxFCSErrors (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "RxGoodOctets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "RxDropPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "RxUnicastPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "RxBroadcastPkts (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "RxSAChanges (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "RxFragments (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "RxJumboPkt (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "RxSymblErr (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "InRangeErrCount (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "OutRangeErrCount (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "EEE_LPI_EVENT (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "EEE_LPI_DURAITON (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "RxDiscard (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "TxQPKTQ6 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "TxQPKTQ7 (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "TxPkts64Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "TxPkts65To127Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "TxPkts128To255Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "TxPkts256To511Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "TxPkts512To1023Octets (port 0)"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "TxPkts1024ToMaxOctets (port 0)"),
};

/* Page 0x21: Port MIB Counter (port 1) Register */
static struct bcmRegDesc bcmPage_21[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "TxOctets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TxDropPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "TxQPKTQ0 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "TxBroadcastPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "TxMulticasePkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "TxUnicastPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "TxCollision (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "TxSingleCollision (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "TxMultipleCollision (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "TxDeferredTransmit (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "TxLateCollision (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "TxExcessiveCollision (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "TxFrameInDisc (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "TxPausePkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "TxQPKTQ1 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "TxQPKTQ2 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "TxQPKTQ3 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "TxQPKTQ4 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "TxQPKTQ5 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "RxOctets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "RxUndersizePkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "RxPausePkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RxPkts64Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RxPkts65To127Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RxPkts128To255Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RxPkts256To511Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RxPkts512To1023Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RxPkts1024ToMaxOctets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RxOversizePkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "RxJabbers (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "RxAlignementErrors (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "RxFCSErrors (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "RxGoodOctets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "RxDropPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "RxUnicastPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "RxBroadcastPkts (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "RxSAChanges (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "RxFragments (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "RxJumboPkt (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "RxSymblErr (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "InRangeErrCount (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "OutRangeErrCount (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "EEE_LPI_EVENT (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "EEE_LPI_DURAITON (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "RxDiscard (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "TxQPKTQ6 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "TxQPKTQ7 (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "TxPkts64Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "TxPkts65To127Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "TxPkts128To255Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "TxPkts256To511Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "TxPkts512To1023Octets (port 1)"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "TxPkts1024ToMaxOctets (port 1)"),
};

/* Page 0x22: Port MIB Counter (port 2) Register */
static struct bcmRegDesc bcmPage_22[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "TxOctets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TxDropPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "TxQPKTQ0 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "TxBroadcastPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "TxMulticasePkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "TxUnicastPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "TxCollision (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "TxSingleCollision (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "TxMultipleCollision (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "TxDeferredTransmit (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "TxLateCollision (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "TxExcessiveCollision (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "TxFrameInDisc (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "TxPausePkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "TxQPKTQ1 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "TxQPKTQ2 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "TxQPKTQ3 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "TxQPKTQ4 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "TxQPKTQ5 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "RxOctets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "RxUndersizePkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "RxPausePkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RxPkts64Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RxPkts65To127Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RxPkts128To255Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RxPkts256To511Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RxPkts512To1023Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RxPkts1024ToMaxOctets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RxOversizePkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "RxJabbers (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "RxAlignementErrors (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "RxFCSErrors (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "RxGoodOctets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "RxDropPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "RxUnicastPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "RxBroadcastPkts (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "RxSAChanges (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "RxFragments (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "RxJumboPkt (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "RxSymblErr (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "InRangeErrCount (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "OutRangeErrCount (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "EEE_LPI_EVENT (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "EEE_LPI_DURAITON (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "RxDiscard (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "TxQPKTQ6 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "TxQPKTQ7 (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "TxPkts64Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "TxPkts65To127Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "TxPkts128To255Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "TxPkts256To511Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "TxPkts512To1023Octets (port 2)"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "TxPkts1024ToMaxOctets (port 2)"),
};

/* Page 0x23: Port MIB Counter (port 3) Register */
static struct bcmRegDesc bcmPage_23[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "TxOctets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TxDropPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "TxQPKTQ0 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "TxBroadcastPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "TxMulticasePkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "TxUnicastPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "TxCollision (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "TxSingleCollision (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "TxMultipleCollision (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "TxDeferredTransmit (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "TxLateCollision (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "TxExcessiveCollision (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "TxFrameInDisc (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "TxPausePkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "TxQPKTQ1 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "TxQPKTQ2 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "TxQPKTQ3 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "TxQPKTQ4 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "TxQPKTQ5 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "RxOctets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "RxUndersizePkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "RxPausePkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RxPkts64Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RxPkts65To127Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RxPkts128To255Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RxPkts256To511Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RxPkts512To1023Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RxPkts1024ToMaxOctets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RxOversizePkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "RxJabbers (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "RxAlignementErrors (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "RxFCSErrors (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "RxGoodOctets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "RxDropPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "RxUnicastPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "RxBroadcastPkts (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "RxSAChanges (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "RxFragments (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "RxJumboPkt (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "RxSymblErr (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "InRangeErrCount (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "OutRangeErrCount (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "EEE_LPI_EVENT (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "EEE_LPI_DURAITON (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "RxDiscard (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "TxQPKTQ6 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "TxQPKTQ7 (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "TxPkts64Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "TxPkts65To127Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "TxPkts128To255Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "TxPkts256To511Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "TxPkts512To1023Octets (port 3)"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "TxPkts1024ToMaxOctets (port 3)"),
};

/* Page 0x25: Port MIB Counter (port 5) Register */
static struct bcmRegDesc bcmPage_25[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "TxOctets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TxDropPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "TxQPKTQ0 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "TxBroadcastPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "TxMulticasePkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "TxUnicastPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "TxCollision (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "TxSingleCollision (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "TxMultipleCollision (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "TxDeferredTransmit (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "TxLateCollision (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "TxExcessiveCollision (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "TxFrameInDisc (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "TxPausePkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "TxQPKTQ1 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "TxQPKTQ2 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "TxQPKTQ3 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "TxQPKTQ4 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "TxQPKTQ5 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "RxOctets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "RxUndersizePkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "RxPausePkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RxPkts64Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RxPkts65To127Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RxPkts128To255Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RxPkts256To511Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RxPkts512To1023Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RxPkts1024ToMaxOctets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RxOversizePkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "RxJabbers (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "RxAlignementErrors (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "RxFCSErrors (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "RxGoodOctets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "RxDropPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "RxUnicastPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "RxBroadcastPkts (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "RxSAChanges (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "RxFragments (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "RxJumboPkt (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "RxSymblErr (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "InRangeErrCount (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "OutRangeErrCount (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "EEE_LPI_EVENT (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "EEE_LPI_DURAITON (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "RxDiscard (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "TxQPKTQ6 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "TxQPKTQ7 (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "TxPkts64Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "TxPkts65To127Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "TxPkts128To255Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "TxPkts256To511Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "TxPkts512To1023Octets (port 5)"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "TxPkts1024ToMaxOctets (port 5)"),
};

/* Page 0x28: Port MIB Counter (IMP port) Register */
static struct bcmRegDesc bcmPage_28[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "TxOctets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TxDropPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "TxQPKTQ0_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "TxBroadcastPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "TxMulticasePkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "TxUnicastPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "TxCollision_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "TxSingleCollision_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "TxMultipleCollision_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "TxDeferredTransmit_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "TxLateCollision_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "TxExcessiveCollision_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "TxFrameInDisc_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "TxPausePkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "TxQPKTQ1_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "TxQPKTQ2_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "TxQPKTQ3_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "TxQPKTQ4_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "TxQPKTQ5_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "RxOctets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "RxUndersizePkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "RxPausePkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RxPkts64Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RxPkts65To127Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RxPkts128To255Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RxPkts256To511Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RxPkts512To1023Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RxPkts1024ToMaxOctets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RxOversizePkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "RxJabbers_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "RxAlignementErrors_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "RxFCSErrors_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "RxGoodOctets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "RxDropPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "RxUnicastPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "RxMulticastPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "RxBroadcastPkts_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "RxSAChanges_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "RxFragments_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "RxJumboPkt_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "RxSymblErr_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "InRangeErrCount_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "OutRangeErrCount_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "EEE_LPI_EVENT_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "EEE_LPI_DURAITON_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "RxDiscard_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "TxQPKTQ6_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "TxQPKTQ7_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "TxPkts64Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "TxPkts65To127Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "TxPkts128To255Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "TxPkts256To511Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "TxPkts512To1023Octets_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "TxPkts1024ToMaxOctets_IMP"),
};

/* Page 0x30: QoS Register */
static struct bcmRegDesc bcmPage_30[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "QOS_GLOBAL_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "QOS_IEEE_802_1P_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "QOS_EN_DIFFSERV"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "PN_PCP2TC_DEI0"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "IMP_PCP2TC_DEI0"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 48, "QOS_DIFF_DSCP0"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 48, "QOS_DIFF_DSCP1"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 48, "QOS_DIFF_DSCP2"),
	BCMREG_REG_DESC_INITIALIZER(0x42, 48, "QOS_DIFF_DSCP3"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "PID2TC"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 16, "TC_SEL_TABLE"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 16, "IMP_TC_SEL_TABLE"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "CPU2COS_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "PN_CPU2COS_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "IMP_CPU2COS_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "PN_PCP2TC_DEI1"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "PN_PCP2TC_DEI1"),
};

/* Page 0x31: Port Based VLAN Register */
static struct bcmRegDesc bcmPage_31[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "PORT_VLAN_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "PORT_VLAN_CTL_IMP"),
};

/* Page 0x32: Trunking Register */
static struct bcmRegDesc bcmPage_32[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "MAC_TRUNK_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "TRUNK_GRP_CTL"),
};

/* Page 0x34: IEEE 802.1Q VLAN Register */
static struct bcmRegDesc bcmPage_34[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "VLAN_CTRL0"),
	BCMREG_REG_DESC_INITIALIZER(0x01, 8, "VLAN_CTRL1"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 8, "VLAN_CTRL2"),
	BCMREG_REG_DESC_INITIALIZER(0x03, 16, "VLAN_CTRL3"),
	BCMREG_REG_DESC_INITIALIZER(0x05, 8, "VLAN_CTRL4"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 8, "VLAN_CTRL5"),
	BCMREG_REG_DESC_INITIALIZER(0x07, 8, "VLAN_CTRL6"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "VLAN_MULTI_PORT_ADDR_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "DEFAULT_1Q_TAG"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "DEFAULT_1Q_TAG_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "DTAG_TPID"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "ISP_SEL_PORTMAP"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "EGRESS_VID_RMK_TBL_ACS"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "EGRESS_VID_RMK_TBL_DATA"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 16, "JOIN_ALL_VLAN_EN"),
	BCMREG_REG_DESC_INITIALIZER(0x52, 16, "PORT_IVL_SVL_CTRL"),
};

/* Page 0x36: DOS Prevent Register */
static struct bcmRegDesc bcmPage_36[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "DOS_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 8, "MINIMUM_TCP_HDR_SZ"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "MAX_ICMPV4_SIZE_REG"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "MAX_ICMPV6_SIZE_REG"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 8, "DOS_DIS_LRN_REG"),
};

/* Page 0x40: Jumbo Frame Control Register */
static struct bcmRegDesc bcmPage_40[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x01, 32, "JUMBO_PORT_MASK"),
	BCMREG_REG_DESC_INITIALIZER(0x05, 16, "MIB_GD_FM_MAX_SIZE"),
};

/* Page 0x41: Common INgress Rate Control Register */
static struct bcmRegDesc bcmPage_41[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "COMM_IRC_CON"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "BC_SUP_RATECTRL_P"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "BC_SUP_RATECTRL_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "BC_SUP_RATECTRL_1_P"),
	BCMREG_REG_DESC_INITIALIZER(0x43, 16, "BC_SUP_RATECTRL_1_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "BC_SUP_PKTDROP_CNT_P"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "BC_SUP_PKTDROP_CMD_IMP"),
};

/* Page 0x42: EAP Control Register */
static struct bcmRegDesc bcmPage_42[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "EAP_GLO_CON"),
	BCMREG_REG_DESC_INITIALIZER(0x01, 8, "EAP_MULTI_ADDR_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 64, "EAP_DIP"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 64, "PORT_EAP_CON"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 64, "PORT_EAP_CON_IMP"),
};

/* Page 0x43: MSPT (Multi Spanning Tree) Control Register */
static struct bcmRegDesc bcmPage_43[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "MSG_CON"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 32, "MSG_AGE"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "MSG_TAB"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 16, "MSG_MULTI_ADDR_BPS_CTRL"),
};

/* Page 0x45: Source MAC Address Limit Control Register */
static struct bcmRegDesc bcmPage_45[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "SA_LIMIT_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "SA_LRN_CNTR_RST"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "SA_OVERLIMIT_CNTR_RST"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "TOTAL_SA_LIMIT_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "PORT_N_SA_LIMIT_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "PORT_8_SA_LIMIT_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "TOTAL_SA_LRN_CTNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "PORT_N_SA_LRN_CTNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x42, 16, "PORT_8_SA_LRN_CTNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "PORT_N_SA_OVERLIMIT_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "PORT_8_SA_OVERLIMIT_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 16, "SA_OVER_LIMIT_COPY_REDIRECT"),
};

/* Page 0x46: Port QoS Priority Control Register */
static struct bcmRegDesc bcmPage_46[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "PN_QOS_PRI_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 8, "IMP_QOS_PRI_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 6, "IMP_QOS_WEIGHT"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 16, "Page 0x47?"),
	BCMREG_REG_DESC_INITIALIZER(0x72, 6, "Page 0x47?"),
};

/* Page 0x47: Port Shaper Control Register */
static struct bcmRegDesc bcmPage_47[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_PORT_SHAPER_BYTE_BASED_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_PORT_SHAPER_BYTE_BASED_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_PORT_SHAPER_BYTE_BASED_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_PORT_SHAPER_BYTE_BASED_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_PORT_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_PORT_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_PORT_SHAPER_PACKET_BASED_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_PORT_SHAPER_PACKET_BASED_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_PORT_SHAPER_PACKET_BASED_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_PORT_SHAPER_PACKET_BASED_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "PORT_SHAPER_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "PORT_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "PORT_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "PORT_SHAPER_BLOCKING"),
	BCMREG_REG_DESC_INITIALIZER(0xee, 16, "IFG_BYTES"),
};

/* Page 0x48: Port Queue 0 Shaper Control Register */
static struct bcmRegDesc bcmPage_48[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE0_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE0_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE0_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE0_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE0_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE0_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE0_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE0_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE0_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE0_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE0_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE0_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE0_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE0_SHAPER_BLOCKING"),
};

/* Page 0x49: Port Queue 1 Shaper Control Register */
static struct bcmRegDesc bcmPage_49[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE1_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE1_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE1_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE1_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE1_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE1_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE1_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE1_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE1_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE1_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE1_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE1_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE1_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE1_SHAPER_BLOCKING"),
};

/* Page 0x4a: Port Queue 2 Shaper Control Register */
static struct bcmRegDesc bcmPage_4a[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE2_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE2_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE2_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE2_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE2_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE2_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE2_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE2_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE2_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE2_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE2_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE2_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE2_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE2_SHAPER_BLOCKING"),
};

/* Page 0x4b: Port Queue 3 Shaper Control Register */
static struct bcmRegDesc bcmPage_4b[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE3_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE3_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE3_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE3_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE3_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE3_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE3_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE3_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE3_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE3_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE3_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE3_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE3_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE3_SHAPER_BLOCKING"),
};

/* Page 0x4c: Port Queue 4 Shaper Control Register */
static struct bcmRegDesc bcmPage_4c[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE4_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE4_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE4_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE4_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE4_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE4_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE4_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE4_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE4_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE4_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE4_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE4_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE4_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE4_SHAPER_BLOCKING"),
};

/* Page 0x4d: Port Queue 5 Shaper Control Register */
static struct bcmRegDesc bcmPage_4d[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE5_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE5_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE5_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE5_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE5_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE5_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE5_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE5_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE5_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE5_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE5_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE5_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE5_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE5_SHAPER_BLOCKING"),
};

/* Page 0x4e: Port Queue 6 Shaper Control Register */
static struct bcmRegDesc bcmPage_4e[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE6_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE6_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE6_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE6_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE6_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE6_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE6_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE6_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE6_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE6_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE6_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE6_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE6_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE6_SHAPER_BLOCKING"),
};

/* Page 0x4f: Port Queue 0 Shaper Control Register */
static const struct bcmRegDesc bcmPage_4f[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "PN_QUEUE7_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "IMP_QUEUE7_MAX_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "PN_QUEUE7_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "IMP_QUEUE7_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "PN_QUEUE7_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "IMP_QUEUE7_SHAPER_STS"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "PN_QUEUE7_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "IMP_QUEUE7_MAX_PACKET_REFRESH"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "PN_QUEUE7_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "IMP_QUEUE7_MAX_THD_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "QUEUE7_AVB_SHAPING_MODE"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "QUEUE7_SHAPER_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0xe8, 16, "QUEUE7_SHAPER_BUCKET_COUNT_SELECT"),
	BCMREG_REG_DESC_INITIALIZER(0xea, 16, "QUEUE7_SHAPER_BLOCKING"),
};

/* Page 0x70: Port MIB Snapshot Control Register */
static const struct bcmRegDesc bcmPage_70[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 8, "MIB_SNAPSHOT_CTL"),
};

/* Page 0x71: Port MIB Snapshot Counter Register */
static const struct bcmRegDesc bcmPage_71[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 64, "S_TxOctets"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "S_TxDropPkts"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "S_TxQPKTQ0"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "S_TxBroadcastPkts"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "S_TxMulticasePkts"),
	BCMREG_REG_DESC_INITIALIZER(0x18, 32, "S_TxUnicastPkts"),
	BCMREG_REG_DESC_INITIALIZER(0x1c, 32, "S_TxCollision"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "S_TxSingleCollision"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 32, "S_TxMultipleCollision"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 32, "S_TxDeferredTransmit"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 32, "S_TxLateCollision"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "S_TxExcessiveCollision"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 32, "S_TxFrameInDisc"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 32, "S_TxPausePkts"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 32, "S_TxQPKTQ1"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 32, "S_TxQPKTQ2"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 32, "S_TxQPKTQ3"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 32, "S_TxQPKTQ4"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 32, "S_TxQPKTQ5"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "S_RxOctets"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "S_RxUndersizePkts"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 32, "S_RxPausePkts"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "S_RxPkts64Octets"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "S_RxPkts65To127Octets"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "S_RxPkts128To255Octets"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "S_RxPkts256To511Octets"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "S_RxPkts512To1023Octets"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "S_RxPkts1024ToMaxOctets"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "S_RxOversizePkts"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "S_RxJabbers"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "S_RxAlignementErrors"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "S_RxFCSErrors"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 64, "S_RxGoodOctets"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "S_RxDropPkts"),
	BCMREG_REG_DESC_INITIALIZER(0x94, 32, "S_RxUnicastPkts"),
	BCMREG_REG_DESC_INITIALIZER(0x98, 32, "S_RxMulticastPkts"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "S_RxBroadcastPkts"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 32, "S_RxSAChanges"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 32, "S_RxFragments"),
	BCMREG_REG_DESC_INITIALIZER(0xa8, 32, "S_RxJumboPkt"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 32, "S_RxSymblErr"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 32, "S_InRangeErrCount"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 32, "S_OutRangeErrCount"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 32, "S_EEE_LPI_EVENT"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 32, "S_EEE_LPI_DURAITON"),
	BCMREG_REG_DESC_INITIALIZER(0xc0, 32, "S_RxDiscard"),
	BCMREG_REG_DESC_INITIALIZER(0xc8, 32, "S_TxQPKTQ6"),
	BCMREG_REG_DESC_INITIALIZER(0xcc, 32, "S_TxQPKTQ7"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 32, "S_TxPkts64Octets"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 32, "S_TxPkts65To127Octets"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 32, "S_TxPkts128To255Octets"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 32, "S_TxPkts256To511Octets"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 32, "S_TxPkts512To1023Octets"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 32, "S_TxPkts1024ToMaxOctets"),
};

/* Page 0x72: Loop Discovery Register */
static const struct bcmRegDesc bcmPage_72[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "LPDET_CFG"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 8, "DF_TIMER"),
	BCMREG_REG_DESC_INITIALIZER(0x03, 16, "LED_PORTMAP"),
	BCMREG_REG_DESC_INITIALIZER(0x05, 48, "MODULE_ID0"),
	BCMREG_REG_DESC_INITIALIZER(0x0b, 48, "MODULE_ID1"),
	BCMREG_REG_DESC_INITIALIZER(0x11, 48, "LPDET_SA"),
};

/* Page 0x85: Port 5 External PHY MII Register */
static const struct bcmRegDesc bcmPage_85[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "G_MIICTL_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "G_MIISTS_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "G_PHYIDH_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "G_PHYIDL_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "G_ANADV_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "G_ANLPA_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "G_ANEXP_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "G_ANNXP_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "G_LPNXP_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "G_B1000T_CTL_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "G_L1000T_STS_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "G_EXT_STS_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "G_PHY_EXT_CTL_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "G_PHY_EXT_STS_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "G_REC_ERR_CNT_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "G_FALSE_CARR_CNT_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "G_REC_NOTOK_CNT_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "G_DSP_COEFFICIENT_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "G_DSP_COEFFICIENT_ADDR_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "G_AUX_CTL_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "G_AUX_STS_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "G_INTERRUPT_STS_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "G_INTERRUPT_MSK_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "G_MISC_SHADOW_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "G_MASTER_SLAVE_SEED_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "G_TEST1_EXT_P5"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "G_TEST2_EXT_P5"),
};

/* Page 0x88: IMP Port External PHY MII Register */
static const struct bcmRegDesc bcmPage_88[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "G_MIICTL_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "G_MIISTS_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "G_PHYIDH_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "G_PHYIDL_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "G_ANADV_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "G_ANLPA_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 16, "G_ANEXP_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "G_ANNXP_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "G_LPNXP_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "G_B1000T_CTL_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 16, "G_L1000T_STS_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x1e, 16, "G_EXT_STS_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "G_PHY_EXT_CTL_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "G_PHY_EXT_STS_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "G_REC_ERR_CNT_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x26, 16, "G_FALSE_CARR_CNT_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "G_REC_NOTOK_CNT_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "G_DSP_COEFFICIENT_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "G_DSP_COEFFICIENT_ADDR_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "G_AUX_CTL_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "G_AUX_STS_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "G_INTERRUPT_STS_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "G_INTERRUPT_MSK_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "G_MISC_SHADOW_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "G_MASTER_SLAVE_SEED_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "G_TEST1_EXT"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "G_TEST2_EXT"),
};

/* Page 0x91: Traffic Remarking Registers */
static const struct bcmRegDesc bcmPage_91[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "TRREG_CTRL0"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 32, "TRREG_CTRL1"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 32, "TRREG_CTRL2"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 64, "PN_EGRESS_PKT_TC2PCP_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 64, "IMP_EGRESS_PKT_TC2PCP_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 64, "PN_EGRESS_PKT_TC2CPCP_MAP"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 64, "IMP_EGRESS_PKT_TC2CPCP_MAP"),
};

/* Page 0x92: EEE Registers */
static const struct bcmRegDesc bcmPage_92[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "EEE_EN_CTRL"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "EEE_LPI_ASSERT"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "EEE_LPI_INDICATE"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "EEE_RX_IDLE_SYMBOL"),
	BCMREG_REG_DESC_INITIALIZER(0x0c, 32, "EEE_PIPELINE_TIMER"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "EEE_SLEEP_TIMER_G"),
	BCMREG_REG_DESC_INITIALIZER(0x54, 32, "EEE_SLEEP_TIMER_H_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "EEE_MIN_LP_TIMER_G"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "EEE_MIN_LP_TIMER_G_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 32, "EEE_MIN_LP_TIMER_H"),
	BCMREG_REG_DESC_INITIALIZER(0x9c, 32, "EEE_MIN_LP_TIMER_H_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 16, "EEE_WAKE_TIMER_G"),
	BCMREG_REG_DESC_INITIALIZER(0xb0, 16, "EEE_WAKE_TIMER_G_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xb2, 16, "EEE_WAKE_TIMER_H"),
	BCMREG_REG_DESC_INITIALIZER(0xc2, 16, "EEE_WAKE_TIMER_H_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0xc4, 16, "EEE_GLB_CONG_TH"),
	BCMREG_REG_DESC_INITIALIZER(0xc6, 16, "EEE_TXQ_CONG_TH"),
	BCMREG_REG_DESC_INITIALIZER(0xd3, 16, "EEE_TXQ_CONG_TH6"),
	BCMREG_REG_DESC_INITIALIZER(0xd5, 16, "EEE_TXQ_CONG_TH7"),
};

/* Page 0x93: 1588 Control Register */
static const struct bcmRegDesc bcmPage_93[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "PORT_ENABLE"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "TX_MODE_PORT"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 16, "TX_MODE_PORT_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "RX_MODE_PORT"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 16, "RX_MODE_PORT_IMP"),
	BCMREG_REG_DESC_INITIALIZER(0x22, 16, "TX_TS_CAP"),
	BCMREG_REG_DESC_INITIALIZER(0x24, 16, "RX_TS_CAP"),
	BCMREG_REG_DESC_INITIALIZER(0x28, 16, "RX_PORT_0_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x2a, 16, "RX_PORT_0_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x2c, 16, "RX_PORT_1_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x2e, 16, "RX_PORT_1_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 16, "RX_PORT_2_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x32, 16, "RX_PORT_2_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x34, 16, "RX_PORT_3_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x36, 16, "RX_PORT_3_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x38, 16, "RX_PORT_4_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x3a, 16, "RX_PORT_4_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x3c, 16, "RX_PORT_5_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x3e, 16, "RX_PORT_5_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x44, 16, "RX_PORT_8_LINK_DELAY_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x46, 16, "RX_PORT_8_LINK_DELAY_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x48, 16, "RX_PORT_0_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x4a, 16, "RX_PORT_0_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x4c, 16, "RX_PORT_1_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x4e, 16, "RX_PORT_1_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 16, "RX_PORT_2_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x52, 16, "RX_PORT_2_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x54, 16, "RX_PORT_3_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x56, 16, "RX_PORT_3_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 16, "RX_PORT_4_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x5a, 16, "RX_PORT_4_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x5c, 16, "RX_PORT_5_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x5e, 16, "RX_PORT_5_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 16, "RX_PORT_8_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x66, 16, "RX_PORT_8_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 16, "TX_PORT_0_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x6a, 16, "TX_PORT_0_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 16, "TX_PORT_1_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x6e, 16, "TX_PORT_1_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 16, "TX_PORT_2_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x72, 16, "TX_PORT_2_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 16, "TX_PORT_3_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x76, 16, "TX_PORT_3_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 16, "TX_PORT_4_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x7a, 16, "TX_PORT_4_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 16, "TX_PORT_5_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x7e, 16, "TX_PORT_5_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 16, "TX_PORT_8_TS_OFFSET_LSB"),
	BCMREG_REG_DESC_INITIALIZER(0x86, 16, "TX_PORT_8_TS_OFFSET_MSB"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 16, "TIME_CODE_N"),
	BCMREG_REG_DESC_INITIALIZER(0xa2, 16, "RX_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0xa4, 16, "RX_TX_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0xa6, 16, "VLAN_ITPID"),
	BCMREG_REG_DESC_INITIALIZER(0xac, 16, "NSE_DPLL_1"),
	BCMREG_REG_DESC_INITIALIZER(0xae, 16, "NSE_DPLL_2_N"),
	BCMREG_REG_DESC_INITIALIZER(0xb4, 16, "NSE_DPLL_3_N"),
	BCMREG_REG_DESC_INITIALIZER(0xb8, 16, "NSE_DPLL_4"),
	BCMREG_REG_DESC_INITIALIZER(0xba, 16, "NSE_DPLL_5"),
	BCMREG_REG_DESC_INITIALIZER(0xbc, 16, "NSE_DPLL_6"),
	BCMREG_REG_DESC_INITIALIZER(0xbe, 16, "NSE_DPLL_7_N"),
	BCMREG_REG_DESC_INITIALIZER(0xc6, 16, "NSE_NCO_1_N"),
	BCMREG_REG_DESC_INITIALIZER(0xca, 16, "NSE_NCO_2_N"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 16, "NSE_NCO_3_0"),
	BCMREG_REG_DESC_INITIALIZER(0xd2, 16, "NSE_NCO_3_1"),
	BCMREG_REG_DESC_INITIALIZER(0xd4, 16, "NSE_NCO_3_2"),
	BCMREG_REG_DESC_INITIALIZER(0xd6, 16, "NSE_NCO_4"),
	BCMREG_REG_DESC_INITIALIZER(0xd8, 16, "NSE_NCO_5_0"),
	BCMREG_REG_DESC_INITIALIZER(0xda, 16, "NSE_NCO_5_1"),
	BCMREG_REG_DESC_INITIALIZER(0xdc, 16, "NSE_NCO_5_2"),
	BCMREG_REG_DESC_INITIALIZER(0xde, 16, "NSE_NCO_6"),
	BCMREG_REG_DESC_INITIALIZER(0xd0, 16, "NSE_NCO_7_0"),
	BCMREG_REG_DESC_INITIALIZER(0xe2, 16, "NSE_NCO_7_1"),
	BCMREG_REG_DESC_INITIALIZER(0xe4, 16, "TX_COUNTER"),
	BCMREG_REG_DESC_INITIALIZER(0xe6, 16, "RX_COUNTER"),
};

/* Page 0x94: Heartbeat Time Stamp Control Register */
static const struct bcmRegDesc bcmPage_94[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "TS_READ_START_END"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "HEARTBEAT_N"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "TIME_STAMP_N"),
	BCMREG_REG_DESC_INITIALIZER(0x0e, 16, "TIME_STAMP_INFO_N"),
	BCMREG_REG_DESC_INITIALIZER(0x12, 16, "CNTR_DBG"),
	BCMREG_REG_DESC_INITIALIZER(0x76, 16, "RX_CF_SPEC"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 16, "TIMECODE_SEL"),
	BCMREG_REG_DESC_INITIALIZER(0x7e, 16, "TIME_STAMP_3"),
};

/* Page 0x95: RED Control Register */
static const struct bcmRegDesc bcmPage_95[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "RED_CONTROL"),
	BCMREG_REG_DESC_INITIALIZER(0x02, 16, "TC2RED_PROFILE_TABLE"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "RED_EGRESS_BYPASS"),
	BCMREG_REG_DESC_INITIALIZER(0x06, 16, "RED_AQD_CONTROL"),
	BCMREG_REG_DESC_INITIALIZER(0x08, 16, "RED_EXPONENT"),
	BCMREG_REG_DESC_INITIALIZER(0x0a, 16, "RED_DROP_ADD_TO_MIB"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "RED_PROFILE_DEFAULT"),
	BCMREG_REG_DESC_INITIALIZER(0x14, 32, "RED_PROFILE_N"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 32, "RED_PROFILE_N"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 16, "RED_DROP_CNTR_RST"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "PN_PORT_RED_PKT_DROP_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 32, "IMP_PORT_RED_PKT_DROP_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 64, "PN_PORT_RED_BYTE_DROP_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0xe0, 64, "IMP_PORT_RED_BYTE_DROP_CNTR"),
};

/* Page 0xa0: CFP TCAM Register */
static const struct bcmRegDesc bcmPage_a0[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 32, "CFP_ACC"),
	BCMREG_REG_DESC_INITIALIZER(0x04, 16, "RATE_METER_GLOBAL_CTL"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 32, "CFP_DATA"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 32, "CFP_MASK"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 32, "ACT_POL_DATA0"),
	BCMREG_REG_DESC_INITIALIZER(0x54, 32, "ACT_POL_DATA1"),
	BCMREG_REG_DESC_INITIALIZER(0x58, 32, "ACT_POL_DATA2"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 32, "RATE_METER0"),
	BCMREG_REG_DESC_INITIALIZER(0x64, 32, "RATE_METER1"),
	BCMREG_REG_DESC_INITIALIZER(0x68, 32, "RATE_METER2"),
	BCMREG_REG_DESC_INITIALIZER(0x6c, 32, "RATE_METER3"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 32, "RATE_METER4"),
	BCMREG_REG_DESC_INITIALIZER(0x74, 32, "RATE_METER5"),
	BCMREG_REG_DESC_INITIALIZER(0x78, 32, "RATE_METER6"),
	BCMREG_REG_DESC_INITIALIZER(0x7c, 16, "TC2COLOR"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 32, "STAT_GREEN_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x84, 32, "STAT_YELLOW_CNTR"),
	BCMREG_REG_DESC_INITIALIZER(0x88, 32, "STAT_RED_CNTR"),
};

/* Page 0xa1: CFP Configuration Register */
static const struct bcmRegDesc bcmPage_a1[] =
{
	BCMREG_REG_DESC_INITIALIZER(0x00, 16, "CFP_CTL_REG"),
	BCMREG_REG_DESC_INITIALIZER(0x10, 8, "UDF_0_A_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x20, 8, "UDF_1_A_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x30, 8, "UDF_2_A_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x40, 8, "UDF_0_B_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x50, 8, "UDF_1_B_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x60, 8, "UDF_2_B_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x70, 8, "UDF_0_C_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x80, 8, "UDF_1_C_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0x90, 8, "UDF_2_C_0_8"),
	BCMREG_REG_DESC_INITIALIZER(0xa0, 8, "UDF_0_1_0_11"),
};

struct bcmPageDesc {
	int pageNum;
	int numRegs;
	const struct bcmRegDesc *regsPtr;
};

#define BCMREG_PAGE_DESC_INITIALIZER(pageNum, regsArray)   \
	{											   \
	pageNum,									\
	ARRAY_SIZE(regsArray),					  \
	regsArray,								  \
	}

static const struct bcmPageDesc bcmPages[] = {
	BCMREG_PAGE_DESC_INITIALIZER(0x00, bcmPage_00),
	BCMREG_PAGE_DESC_INITIALIZER(0x01, bcmPage_01),
	BCMREG_PAGE_DESC_INITIALIZER(0x02, bcmPage_02),
	BCMREG_PAGE_DESC_INITIALIZER(0x03, bcmPage_03),
	BCMREG_PAGE_DESC_INITIALIZER(0x04, bcmPage_04),
	BCMREG_PAGE_DESC_INITIALIZER(0x05, bcmPage_05),
	BCMREG_PAGE_DESC_INITIALIZER(0x10, bcmPage_10),
	BCMREG_PAGE_DESC_INITIALIZER(0x11, bcmPage_11),
	BCMREG_PAGE_DESC_INITIALIZER(0x12, bcmPage_12),
	BCMREG_PAGE_DESC_INITIALIZER(0x13, bcmPage_13),
	BCMREG_PAGE_DESC_INITIALIZER(0x14, bcmPage_14),
	BCMREG_PAGE_DESC_INITIALIZER(0x20, bcmPage_20),
	BCMREG_PAGE_DESC_INITIALIZER(0x21, bcmPage_21),
	BCMREG_PAGE_DESC_INITIALIZER(0x22, bcmPage_22),
	BCMREG_PAGE_DESC_INITIALIZER(0x23, bcmPage_23),
	BCMREG_PAGE_DESC_INITIALIZER(0x25, bcmPage_25),
	BCMREG_PAGE_DESC_INITIALIZER(0x28, bcmPage_28),
	BCMREG_PAGE_DESC_INITIALIZER(0x30, bcmPage_30),
	BCMREG_PAGE_DESC_INITIALIZER(0x31, bcmPage_31),
	BCMREG_PAGE_DESC_INITIALIZER(0x32, bcmPage_32),
	BCMREG_PAGE_DESC_INITIALIZER(0x34, bcmPage_34),
	BCMREG_PAGE_DESC_INITIALIZER(0x36, bcmPage_36),
	BCMREG_PAGE_DESC_INITIALIZER(0x40, bcmPage_40),
	BCMREG_PAGE_DESC_INITIALIZER(0x41, bcmPage_41),
	BCMREG_PAGE_DESC_INITIALIZER(0x42, bcmPage_42),
	BCMREG_PAGE_DESC_INITIALIZER(0x43, bcmPage_43),
	BCMREG_PAGE_DESC_INITIALIZER(0x45, bcmPage_45),
	BCMREG_PAGE_DESC_INITIALIZER(0x46, bcmPage_46),
	BCMREG_PAGE_DESC_INITIALIZER(0x47, bcmPage_47),
	BCMREG_PAGE_DESC_INITIALIZER(0x48, bcmPage_48),
	BCMREG_PAGE_DESC_INITIALIZER(0x49, bcmPage_49),
	BCMREG_PAGE_DESC_INITIALIZER(0x4a, bcmPage_4a),
	BCMREG_PAGE_DESC_INITIALIZER(0x4b, bcmPage_4b),
	BCMREG_PAGE_DESC_INITIALIZER(0x4c, bcmPage_4c),
	BCMREG_PAGE_DESC_INITIALIZER(0x4d, bcmPage_4d),
	BCMREG_PAGE_DESC_INITIALIZER(0x4e, bcmPage_4e),
	BCMREG_PAGE_DESC_INITIALIZER(0x4f, bcmPage_4f),
	BCMREG_PAGE_DESC_INITIALIZER(0x70, bcmPage_70),
	BCMREG_PAGE_DESC_INITIALIZER(0x71, bcmPage_71),
	BCMREG_PAGE_DESC_INITIALIZER(0x72, bcmPage_72),
	BCMREG_PAGE_DESC_INITIALIZER(0x85, bcmPage_85),
	BCMREG_PAGE_DESC_INITIALIZER(0x88, bcmPage_88),
	BCMREG_PAGE_DESC_INITIALIZER(0x91, bcmPage_91),
	BCMREG_PAGE_DESC_INITIALIZER(0x92, bcmPage_92),
	BCMREG_PAGE_DESC_INITIALIZER(0x93, bcmPage_93),
	BCMREG_PAGE_DESC_INITIALIZER(0x94, bcmPage_94),
	BCMREG_PAGE_DESC_INITIALIZER(0x95, bcmPage_95),
	BCMREG_PAGE_DESC_INITIALIZER(0xa0, bcmPage_a0),
	BCMREG_PAGE_DESC_INITIALIZER(0xa1, bcmPage_a1),
};

#define MAX_BCM53134P_PORTS 9

struct bcm53134p_port {
	ofnode phyNode;
	int	isImp;
	int	isSgmii;
};

struct bcm53134p_spi_plat {
	struct bcm53134p_port ports[MAX_BCM53134P_PORTS];
};

/* Following structure used to initialize SGMII port.
 * Note: register names/are provided where documentation
 *	   describes the register page/offset/field. "???"
 *	   is unused in cases where there is no available
 *	   documentaiton.  Configuration sequence discovered
 *	   on broadcom community forum (and confirmed by Broadcom).
 * See: https://community.broadcom.com/t5/Ethernet-Switch/SGMII-SFP-fiber-module-on-BCM53134/m-p/97587/highlight/true#M167
 */
struct Bcm53InitializerEntry {
	uint8_t regPage;   /* BCM53134P register page */
	uint8_t regOffset; /* BCM53134P register offset */
	uint8_t numBits;   /* Number of bits to write */
	uint32_t bitValue; /* Bit value to write (LSB first) */
};

struct Bcm53InitializerEntry bcm53SGMIIinitializerTable[] = {
	{
		/* Control Register::STS_OVERRIDE_P5
		 * override to 1000Mb/s, full duplex and link up  */
		0x00, 0x5d, 8, 0x4b,
	},
	{
		/* ??? */
		0xe6, 0x00, 8, 0x01,
	},
	{
		/* ??? */
		0x14, 0x3e, 16, 0x0080,
	},
	{
		/* ??? */
		0x14, 0x20, 16, 0x2f0c,
	},
	{
		/* ??? */
		0x14, 0x3e, 16, 0x0083,
	},
	{
		/* ??? */
		0x14, 0x20, 16, 0x0d01,
	},
	{
		/* ??? */
		0x14, 0x3e, 16, 0x7084,
	},
	{
		/* ??? */
		0x14, 0x26, 16, 0x5112,
	},
	{
		/* ??? */
		0x14, 0x3e, 16, 0x4083,
	},
	{
		/* ??? */
		0x14, 0x34, 16, 0x0300,
	},
	{
		/* ??? */
		0x14, 0x3e, 16, 0x0080,
	},
	{
		/* ??? */
		0x14, 0x00, 16, 0x4001,
	},
	{
		/* ??? */
		0x14, 0x20, 16, 0x2f2c,
	},
	{
		/* ??? */
		0x14, 0x00, 16, 0x4013,
	},
};

static int   		bitlen;
static uchar 		dout[MAX_SPI_BYTES];
static uchar 		din[MAX_SPI_BYTES];

/* Number of iterations to wait for SPIF bit in SPI_STATUS_REG to clear */
#define SPI_WAIT_FOR_SPIF_COUNT  10

/* Number of iterations to wait for RACK bit in SPI_STATUS_REG to set */
#define SPI_WAIT_FOR_RACK_COUNT  10

/* Number of SPI bits in a set of bytes */
#define NUM_BITS_IN_TWO_BYTES		(2 * 8) /* count of bits in two bytes */
#define NUM_BITS_IN_THREE_BYTES		(3 * 8) /* count of bits in three bytes */

/**
 * Read <bitlen> bits from page <page> register <reg>
 */
int bcm53_spi_rd_xfer(struct udevice *dev, int page, int reg,
					  int bitlen, uchar *din)
{
	int ret = 0;
	int count = 0;
	uchar status_out[3], status_in[3];
	uchar page_out[3], page_in[3];
	uchar reg_out[3], reg_in[3];
	uchar result_out[2+8], result_in[2+8];
	int byteCnt = (bitlen + 7) / 8;
	int i;

	if (!din)
	{
		/* No place to store the read bytes */
		return -1;
	}

	ret = dm_spi_claim_bus(dev);
	if (ret)
		goto done;

	/* 1: setup read SPI_STATUS_REG until SPIF is set */
	count=0;
	do {
		status_out[0] = BCM53_SPI_READ_CMD;   /* 1st byte is read cmd */
		status_out[1] = BCM53_SPI_STATUS_REG; /* 2nd byte is status reg id */
		status_out[2] = 0x00;				 /* 2rd byte contains status bits */
		ret = dm_spi_xfer(dev, NUM_BITS_IN_THREE_BYTES, status_out, status_in,
						  SPI_XFER_BEGIN | SPI_XFER_END);
		DUMP_BITS("1: status", status_out, status_in, NUM_BITS_IN_THREE_BYTES);
		ABORT_ON_ERROR(ret, done);
		if (++count == SPI_WAIT_FOR_SPIF_COUNT)
		{
				/* SPIF flag failed to clear in time */
			ABORT_ON_ERROR(-1, done);
		}
	} while ((status_in[2] & BCM53_SPI_STATUS_SPIF) != 0);

	/* 2: write SPI_PAGE_REG with page */
	page_out[0] = BCM53_SPI_WRITE_CMD; /* 1st byte is write cmd */
	page_out[1] = BCM53_SPI_PAGE_REG;  /* 2nd byte is page reg id */
	page_out[2] = page;				/* 3rd byte is page number */
	ret = dm_spi_xfer(dev, NUM_BITS_IN_THREE_BYTES, page_out, page_in,
					  SPI_XFER_BEGIN | SPI_XFER_END);
	DUMP_BITS("2: page", page_out, page_in, NUM_BITS_IN_THREE_BYTES);
	ABORT_ON_ERROR(ret, done);

	/* 3: setup read to SPI_DATA_REG with register */
	reg_out[0] = BCM53_SPI_READ_CMD; /* 1st byte is read cmd */
	reg_out[1] = reg;				/* 2nd byte is register offset */
	reg_out[2] = 0x00;			   /* 3rd byte is dummy read */
	ret = dm_spi_xfer(dev, NUM_BITS_IN_THREE_BYTES, reg_out, reg_in,
					  SPI_XFER_BEGIN | SPI_XFER_END);
	DUMP_BITS("3: reg", reg_out, reg_in, NUM_BITS_IN_THREE_BYTES);
	ABORT_ON_ERROR(ret, done);

	/* 4: setup read SPI_STATUS_REG until RACK is set */
	count=0;
	do {
		status_out[0] = BCM53_SPI_READ_CMD;   /* 1st byte is read cmd */
		status_out[1] = BCM53_SPI_STATUS_REG; /* 2nd byte is status reg */
		status_out[2] = 0x00;				 /* 3rd byte will contain status bits */
		ret = dm_spi_xfer(dev, NUM_BITS_IN_THREE_BYTES, status_out, status_in,
						  SPI_XFER_BEGIN | SPI_XFER_END);
		DUMP_BITS("4: status", status_out, status_in, NUM_BITS_IN_THREE_BYTES);
		ABORT_ON_ERROR(ret, done);
		if (++count == SPI_WAIT_FOR_RACK_COUNT)
		{
			ABORT_ON_ERROR(-1, done);
		}
	} while ((status_in[2] & BCM53_SPI_STATUS_RACK) != 0);
	/* 5: setup read SPI_DATA_REG and read bitlen/8 out (MSB first) */
	result_out[0] = BCM53_SPI_READ_CMD; /* 1st byte is read cmd */
	result_out[1] = BCM53_SPI_DATA_REG; /* 2nd byte is data reg id */
	for (i=0; i<byteCnt; ++i)
		{
		result_out[i+2] = 0x00;		 /* rest of bytes will have data */
		}

	ret = dm_spi_xfer(dev, NUM_BITS_IN_TWO_BYTES + bitlen, result_out, result_in,
					  SPI_XFER_BEGIN | SPI_XFER_END);
	DUMP_BITS("5: result", result_out, result_in, NUM_BITS_IN_TWO_BYTES + bitlen);
	ABORT_ON_ERROR(ret, done);
		/* Return the result.  Note the register bytes arrive in little-endian
		 * order starting at the 3rd byte; copy them in reverse */

	for (i=0; i<byteCnt; ++i)
	{
		din[i] = result_in[(byteCnt - i - 1) + 2];
	}

done:
	dm_spi_release_bus(dev);

	return ret;

}

/**
 * Write <bitlen> bits of <bits> to page <page> register <reg>
 */
int bcm53_spi_wr_xfer(struct udevice *dev, int page, int reg,
					  int bitlen, uchar *bits)
{
	int ret = 0;
	int count = 0;
	uchar status_out[3], status_in[3];
	uchar page_out[3], page_in[3];
	uchar result_out[2+8], result_in[2+8];
	int byteCnt = (bitlen + 7) / 8;
	int i;

	ret = dm_spi_claim_bus(dev);
	if (ret)
		goto done;

	/* 1: setup read SPI_STATUS_REG until SPIF is set */
	count=0;
	do {
		status_out[0] = BCM53_SPI_READ_CMD;   /* 1st byte is read cmd */
		status_out[1] = BCM53_SPI_STATUS_REG; /* 2nd byte is status reg */
		status_out[2] = 0x00;				 /* 3rd byte will contain status bits */
		ret = dm_spi_xfer(dev, NUM_BITS_IN_THREE_BYTES, status_out, status_in,
						  SPI_XFER_BEGIN | SPI_XFER_END);
		DUMP_BITS("1: status", status_out, status_in, NUM_BITS_IN_THREE_BYTES);
		ABORT_ON_ERROR(ret, done);
		if (++count == SPI_WAIT_FOR_SPIF_COUNT)
		{
			ABORT_ON_ERROR(-1, done);
		}
	} while ((status_in[2] & BCM53_SPI_STATUS_SPIF) != 0);

	/* 2: write SPI_PAGE_REG with page */
	page_out[0] = BCM53_SPI_WRITE_CMD; /* 1st byte is write cmd */
	page_out[1] = BCM53_SPI_PAGE_REG;  /* 2nd byte is page reg id */
	page_out[2] = page;				/* 3rd byte is page */
	ret = dm_spi_xfer(dev, NUM_BITS_IN_THREE_BYTES, page_out, page_in,
					  SPI_XFER_BEGIN | SPI_XFER_END);
	DUMP_BITS("2: page", page_out, page_in, NUM_BITS_IN_THREE_BYTES);
	ABORT_ON_ERROR(ret, done);

	/* 3: setup write to reg and write bitlen/8 out (MSB first) */
	result_out[0] = BCM53_SPI_WRITE_CMD; /* 1st byte is write */
	result_out[1] = reg;				 /* 2nd byte is register offset */
	for (i=0; i<byteCnt; ++i)
	{
			/* 3rd and on bytes in result_out are the data to write
			 * in little endian order */
		result_out[i+2] = bits[(byteCnt - 1) - i];
	}

	ret = dm_spi_xfer(dev, NUM_BITS_IN_TWO_BYTES + bitlen, result_out, result_in,
					  SPI_XFER_BEGIN | SPI_XFER_END);
	DUMP_BITS("3: result", result_out, result_in, NUM_BITS_IN_TWO_BYTES + bitlen);
	ABORT_ON_ERROR(ret, done);

done:
	dm_spi_release_bus(dev);

	return ret;
}

/*
 * Check if IMP 0 port is enabled; and if not then modify registers to enable it
 */
static int bcm53134p_enable_imp0_port(struct udevice *dev)
{
	uchar din[MAX_SPI_BYTES];
	uchar dout[MAX_SPI_BYTES];
	int   ret, page, reg;

	page = 0x00;
	reg = 0x08;
	ret = bcm53_spi_rd_xfer(dev, page, reg, 8, din);
	if (ret)
	{
		printf("%s: failed to read IMP Port Traffic Control Register\n", __func__);
		return 1;
	}
	printf("%s: %02x/%02x: %02x\n", __func__, page, reg, din[0]);

	if ((din[0] & 0x1c) == 0)
	{
		printf("%s: Enable IMP port\n", __func__);
	
		dout[0] = 0x1c;
		ret = bcm53_spi_wr_xfer(dev, 0x00, 0x08, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
		dout[0] = 0x07;
		ret = bcm53_spi_wr_xfer(dev, 0x00, 0x0b, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
		dout[0] = 0x8b;
		ret = bcm53_spi_wr_xfer(dev, 0x00, 0x0e, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
		dout[0] = 0x82;
		ret = bcm53_spi_wr_xfer(dev, 0x02, 0x00, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
		dout[0] = 0x00;
		ret = bcm53_spi_wr_xfer(dev, 0x00, 0x05, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
		dout[0] = 0x03;
		ret = bcm53_spi_wr_xfer(dev, 0x00, 0x60, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
		dout[0] = 0x8b;
		ret = bcm53_spi_wr_xfer(dev, 0x00, 0x0e, 8, dout);
		if (ret)
		{
			printf("%s:%d\n", __func__, __LINE__);
			return 1;
		}
	}

	return 0;
}

static int bcm53134p_port5_sgmii_access(struct udevice *dev)
{
	int	  ret, idx;
	uint32_t bits;

	/* Program the bcm53134p to allow SGMII access to optical port */
	printf("%s: Configure bcm53134p SGMII access...\n", __func__);
	for (idx = 0; idx < ARRAY_SIZE(bcm53SGMIIinitializerTable); ++idx)
	{
		struct Bcm53InitializerEntry *p = &bcm53SGMIIinitializerTable[idx];
		for (bits = 0; bits < p->numBits; bits += 8)
		{
			dout[bits/8] = (p->bitValue >> bits) & 0xff;
		}
		ret = bcm53_spi_wr_xfer(dev, p->regPage, p->regOffset, p->numBits, dout);
		if (ret)
		{
			printf("%s:%d failed to write %d bits to BCM page=0x%02x offset=0x%02x with %#x\n", __func__, __LINE__, p->numBits, p->regPage, p->regOffset, p->bitValue);
			return 1;
		}
	}

	return 0;
}

/* Access the internal PHYs of the BCM switch by means of SPI */
static int bcm53_phy_read(struct mii_dev *bus, int phyaddr,
						  int dev_addr, int regaddr)
{
	u16 reg;
	int ret;
	struct udevice *dev = (struct udevice*)bus->priv;

	if (phyaddr < 0 || phyaddr >= BCM53_NR_OF_PHYS)
	{
		return -1;
	}

	ret = bcm53_spi_rd_xfer(dev, BCM53_INTER_GPHY_REGISTER_BASE + phyaddr,
							regaddr * 2, 8 * sizeof(reg), (uchar*) &reg);

	if (ret)
	{
		return -1;
	}

	return __be16_to_cpu(reg);
}

/* Access the internal PHYs of the BCM switch by means of SPI */
static int bcm53_phy_write(struct mii_dev *bus, int phyaddr,
						   int dev_addr, int regaddr, u16 data)
{
	u16 reg;
	int ret;
	struct udevice *dev  = (struct udevice*)bus->priv;

	if (phyaddr < 0 || phyaddr >= BCM53_NR_OF_PHYS)
	{
		return -1;
	}

	reg = __cpu_to_be16(data);

	ret = bcm53_spi_wr_xfer(dev, BCM53_INTER_GPHY_REGISTER_BASE + phyaddr,
							regaddr * 2, 8 * sizeof(reg), (uchar*) &reg);

	if (ret)
	{
		return -1;
	}

	return 0;
}

static int bcm53134p_spi_probe(struct udevice *dev)
{
	uint32_t					device_id, port_no, phy_addr;
	uint8_t				 		chip_revid, control;
	int							ret;
	ofnode						port_node;
	struct ofnode_phandle_args  phandle;
	struct mii_dev			   *mdio_bus;
	const char				   *status;
	struct phy_device		   *phydev;
	struct gpio_desc            gpio;

	ret = bcm53_spi_rd_xfer(dev, 0x02, 0x30, 8 * sizeof(device_id), (uchar*) &device_id);
	if (!ret)
		ret = bcm53_spi_rd_xfer(dev, 0x02, 0x40, 8 * sizeof(chip_revid), (uchar*) &chip_revid);

	if (ret)
	{
		printf("BCM53134P probe FAILED\n");

		return -ENODEV;
	}
	else
	{
		printf("BCM53134P: device_id 0x%x chip_revid 0x%x\n",
			   __be32_to_cpu(device_id), chip_revid);
	}

	/* Create a (simulated) MDIO bus. In order to use the phy library */
	/* it is required to have a MDIO bus to access phy registers.     */
	mdio_bus = mdio_alloc();
	if (!mdio_bus) {
		printf("mdio_alloc failed\n");
		return -1;
	}

	mdio_bus->read = bcm53_phy_read;
	mdio_bus->write = bcm53_phy_write;
	mdio_bus->priv = dev;
	strncpy(mdio_bus->name, "BCM", sizeof(mdio_bus->name) - 1);
	mdio_bus->name[sizeof(mdio_bus->name) - 1] = '\0';

	ret = mdio_register(mdio_bus);
	if (ret) {
		printf("mdio_register failed\n");
		free(mdio_bus);
		return -1;
	}

	/* SW reset the switch */
	control = 0xc0;
	bcm53_spi_wr_xfer(dev, 0x00, 0x79, 8, &control);
	/* Wait for reset to complete */
	do
	{
		mdelay(10);
		bcm53_spi_rd_xfer(dev, 0x00, 0x79, 8, &control);
	} while ((control & 0x80) == 0x80);

	for (port_node = dev_read_first_subnode(dev);
		 ofnode_valid(port_node);
		 port_node = ofnode_next_subnode(port_node))
	{
		ret = ofnode_read_u32(port_node, "reg", &port_no);
		if (ret)
		{
			continue;
		}

		if (port_no < 4)
		{
			status = ofnode_read_string(port_node, "status");
			if (strcmp(status, "disabled") == 0)
			{
				/* Disable the port */
				control = 0x03;
				ret = bcm53_spi_wr_xfer(dev, 0x00, port_no, 8, &control);
				continue;
			}
			else
			{
				/* Enable the port */
				control = 0x00;
				ret = bcm53_spi_wr_xfer(dev, 0x00, port_no, 8, &control);
			}
		}

		/* Check if port has an associated phy */
		ret = ofnode_parse_phandle_with_args(port_node, "phy-handle", NULL,
											 0, 0, &phandle);

		if (!ret)
		{
			/* Get phy address on mdio bus */
			ret = ofnode_read_u32(phandle.node, "reg", &phy_addr);
			if (!ret)
			{	
				phydev = phy_connect(mdio_bus, phy_addr,
									 dev, PHY_INTERFACE_MODE_NA);

				if (phydev)
				{
					genphy_startup(phydev);
				}
			}
		}

		if (port_no == 5)
		{
			bcm53134p_port5_sgmii_access(dev);

			/* Enable optics if the node has a "enable-optics-gpios" */
			/* property                                              */
			ret = gpio_request_by_name_nodev(port_node, "enable-optics-gpios",
			                                 0, &gpio, GPIOD_IS_OUT);

			if (!ret)
			{
				dm_gpio_set_value(&gpio, 1);
			}

		}

		if (port_no == 8)
		{
			bcm53134p_enable_imp0_port(dev);
		}
	}

	return 0;
}

static const struct udevice_id dm_bcm53134p_spi_match[] = {
	{ .compatible = "brcm,bcm53134p" },
	{ }
};

U_BOOT_DRIVER(bcm53134p_spi) = {
	.name = "bcm53134p_spi",
	.id = UCLASS_MISC,
	.of_match = dm_bcm53134p_spi_match,
	.probe = bcm53134p_spi_probe,
	.plat_auto = sizeof(struct bcm53134p_spi_plat),
};

static struct udevice *dev = NULL;

/*
 * b53 cmd type
 */
enum bcm53CmdType {
	BCM53_CMD_NONE,
	BCM53_CMD_READ,  /* 'rd' */
	BCM53_CMD_WRITE, /* 'wr' */
	BCM53_CMD_DUMP,  /* 'dump' */
};

/* Dump a single page of registers in the BCM53143P */
int bcm53_dump_page(struct udevice *dev, int page)
{
	const struct bcmPageDesc *bcmPagePtr;
	int i, j, k;
	int ret = 0;
	uchar 		din[MAX_SPI_BYTES];

	for (i = 0; i < ARRAY_SIZE(bcmPages); ++i)
	{
		if (bcmPages[i].pageNum == page)
		{
			break;
		}
	}
	if (i == ARRAY_SIZE(bcmPages))
	{
		return 1;
	}

	printf("Page 0x%02x\n", page);

	bcmPagePtr = &bcmPages[i];
	for (j = 0; j < bcmPagePtr->numRegs; ++j)
	{
		const struct bcmRegDesc *p = bcmPagePtr->regsPtr + j;
		int nBytes = (p->bitWidth + 7) / 8;

		ret = bcm53_spi_rd_xfer(dev, page, p->regOffset, p->bitWidth, din);
		if (ret)
		{
			printf("Failed to read page/reg 0x%02x/0x%02x\n", page, p->regOffset);
			return 1;
		}
		printf("0x%02x %40s: ", p->regOffset, p->name);
		for (k = 0; k < nBytes; ++k)
		{
			printf("%02x", din[k]);
		}
		printf("\n");
	}
	return 0;
}

/*
 * B53 register dump/read/write via SPI
 *
 * Syntax:
 *   b53 dump {page}
 *   b53 wr {page} {reg} {bits} {dout}
 *   b53 rd {page} {reg} {bits}
 *	 {page} is the BCM53xx page numer
 *	 {reg} is the BCM53xx reigster offset
 *	 {bits} is number of bits to write/read
 *	 {dout} is a hexadecimal string of data to write
 * The command reads/writes BCM53xx registers
 */

int do_bcm53_spi(struct cmd_tbl *cmdtp, int flag, int argc, char * const argv[])
{
	int page, reg;
	int off, ret = 0;
	uchar tmp;
	char *cp;
	int i, j;
	enum bcm53CmdType cmdType = BCM53_CMD_NONE;

	/* If off is less than 0 the board does not have BCM53134P */
	if (dev == NULL)
	{
		off = fdt_path_offset(gd->fdt_blob, "bcm53134p");

		if (off >= 0)
		{
			/* uclass_get_device_by_of_offset will probe the BCM53134P */
			/* The probe will initialize the BCM53134P                 */
			ret = uclass_get_device_by_of_offset(UCLASS_MISC, off, &dev);

			if (ret)
			{
				return CMD_RET_FAILURE;
			}
		}
		else
		{
	   		printf("Board doesn't have a BCM53134P switch\n");
			return CMD_RET_FAILURE;
		}
	}

	if (argc < 2)
	{
		printf("Not enough args\n");
		return CMD_RET_USAGE;
	}

	if (strcmp(argv[1], "dump") == 0)
	{
		if (argc < 3)
		{
			printf("Not enough read args\n");
			return CMD_RET_USAGE;
		}
		cmdType = BCM53_CMD_DUMP;
	}
	else if (strcmp(argv[1], "rd") == 0)
	{
		if (argc < 5)
		{
			printf("Not enough read args\n");
			return CMD_RET_USAGE;
		}
		cmdType = BCM53_CMD_READ;
   	 }
   	 else if (strcmp(argv[1], "wr") == 0)
   	 {
		if (argc < 6)
		{
			printf("Not enough write args\n");
			return CMD_RET_USAGE;
		}
		cmdType = BCM53_CMD_WRITE;
   	 }
   	 else
   	 {
		printf("Unknown command '%s'\n", argv[1]);
		return CMD_RET_USAGE;
   	 }

   	 if (cmdType == BCM53_CMD_DUMP)
   	 {
		/* Dump takes page, but it can be "all" */
		if (strcmp(argv[2], "all") == 0)
		{
			page = -1;
		}
		else
		{
			page = (int)simple_strtoul(argv[2], NULL, 0);
		}
	}
	else
	{
		page = (int)simple_strtoul(argv[2], NULL, 0);
		reg = (int)simple_strtoul(argv[3], NULL, 0);
		bitlen = (int)simple_strtoul(argv[4], NULL, 0);

		if ((bitlen < 0) || (bitlen >  (MAX_SPI_BYTES * 8))) {
			printf("Invalid bitlen %d\n", bitlen);
			return CMD_RET_FAILURE;
		}
	}

	switch(cmdType)
	{
	case BCM53_CMD_DUMP:
		if (page == -1)
		{
			/* Dump everything in bcmPages */
			for (i = 0; i < ARRAY_SIZE(bcmPages); ++i)
			{
				(void)bcm53_dump_page(dev, bcmPages[i].pageNum);
				if (i != (ARRAY_SIZE(bcmPages) - 1))
				{
					printf("\n");
				}
			}
		}
		else
		{
			/* just dump page in bcmPages */
			ret = bcm53_dump_page(dev, page);
			if (ret)
			{
				printf("Illegal page %d\n", page);
				return CMD_RET_FAILURE;
			}
		}
		break;

	case BCM53_CMD_READ:
		if (bitlen > 64)
		{
			printf("Max register size is 64 bits\n");
			return CMD_RET_FAILURE;
		}
		ret = bcm53_spi_rd_xfer(dev, page, reg, bitlen, din);
		printf("Result: 0x");
		for (i=0; i<bitlen/8; ++i)
		{
			printf("%02x", din[i]);
		}
		printf("\n");
		break;

	case BCM53_CMD_WRITE:
		cp = argv[5];
		for(j = 0; *cp; j++, cp++) {
			if ((*cp >= 'a') && (*cp <= 'f'))
			{
				/* lower case hex character */
				tmp = *cp - 'a' + 10;
			} else if ((*cp >= 'A') && (*cp <= 'F'))
			{
				/* upper case hex character */
				tmp = *cp - 'A' + 10;
			}
			else if ((*cp >= '0') && (*cp <= '9'))
			{
				/* decimal digit */
				tmp = *cp - '0';
			}
			else
			{
				printf("Hex conversion error on %c\n", *cp);
				return CMD_RET_FAILURE;
			}
			if (j/2 >= MAX_SPI_BYTES)
			{
				printf("Supplied hex string too long\n");
				return CMD_RET_FAILURE;
			}

			/* Store hex nybble in appropriate half of byte
			 * (even in high nybble, odd in low nybble) */
			if((j % 2) == 0)
				dout[j / 2] = (tmp << 4);
			else
				dout[j / 2] |= tmp;
		}

		ret = bcm53_spi_wr_xfer(dev, page, reg, bitlen, dout);
		break;
	default:
		printf("%s: illegal cmdType %d\n", __func__, (int)cmdType);
		return CMD_RET_FAILURE;
	}


	return CMD_RET_SUCCESS;
}

U_BOOT_CMD(
	bcm53,	6,	1,	do_bcm53_spi,
	"BCM53xxx SPI interface command",
	"dump <page> - Dump all registers in <page>\n"
	"dump all - Dump all registers in _all_ pages\n"
	"wr <page> <reg> <bits> <dout> - Write <bits> of <dout> hex to register <reg> of page <page>\n"
	"rd <page> <reg> <bits>  - Read/dump <bits> from register <reg> of page <page>\n"
);
