#
# (C) Copyright 2015 Draeger and Licensors, info@draeger.com
#
# SPDX-License-Identifier:        GPL-2.0+
#

obj-y  := mx6m48.o
obj-$(CONFIG_SPL_BUILD) += mx6m48_spl.o mx6m48dl_spl_cfg.o mx6m48q_spl_cfg.o
